USE LAS;

ALTER TABLE users
    ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE AFTER status;

ALTER TABLE students
    ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE AFTER status;

ALTER TABLE departments
    ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE AFTER is_active;

ALTER TABLE institutions
    ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE AFTER is_active;

ALTER TABLE application_windows
    ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE AFTER is_active;

ALTER TABLE specializations
    ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE AFTER is_active;